use crate::geom::{Affine2, BBox, Point, Span};

/// Canonical IPC layout graph.
///
/// IPC-2581 stores panelization as reusable `Step` definitions plus
/// `StepRepeat` placements. This graph mirrors that model directly: `steps`
/// are reusable definitions, `repeats` are compact placement edges, and
/// `instances` are the materialized placements generated by each repeat.
/// Flattened board or board-array geometry is a derived export/rendering
/// view, not independent IR state.
#[derive(Debug, Clone)]
pub struct LayoutGraph<Symbol> {
    /// Root step selected by IPC Content/StepRef or by parser fallback.
    pub root_step: Option<u32>,
    /// Reusable step definitions. Indices are referenced by repeats and instances.
    pub steps: Vec<LayoutStep<Symbol>>,
    /// Compact parent-to-child repeat records. Instances for one repeat are contiguous.
    pub repeats: Vec<LayoutRepeat<Symbol>>,
    /// Materialized placements. Nested panel children reference their parent instance.
    pub instances: Vec<LayoutInstance<Symbol>>,
}

impl<Symbol> Default for LayoutGraph<Symbol> {
    fn default() -> Self {
        Self {
            root_step: None,
            steps: Vec::new(),
            repeats: Vec::new(),
            instances: Vec::new(),
        }
    }
}

impl<Symbol> LayoutGraph<Symbol> {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn is_empty(&self) -> bool {
        self.root_step.is_none()
            && self.steps.is_empty()
            && self.repeats.is_empty()
            && self.instances.is_empty()
    }
}

/// Reusable IPC step definition.
///
/// A step owns its local profile/layer features. A board array is represented
/// by a panel step with child board instances, not by duplicating board data.
#[derive(Debug, Clone)]
pub struct LayoutStep<Symbol> {
    pub source_step_ref: Symbol,
    pub kind: LayoutStepKind,
    pub datum: Point,
    /// Spans `doc.profiles`.
    pub profiles: Span,
    pub bbox: BBox,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LayoutStepKind {
    Board,
    Panel,
    Coupon,
    Tooling,
    Ic,
    Unknown,
}

/// Compact placement edge from a parent step or parent instance to a child step.
#[derive(Debug, Clone)]
pub struct LayoutRepeat<Symbol> {
    pub parent_step: u32,
    pub parent_instance: Option<u32>,
    pub child_step: u32,
    pub source_step_ref: Symbol,
    pub x: f64,
    pub y: f64,
    pub nx: u32,
    pub ny: u32,
    pub dx: f64,
    pub dy: f64,
    pub angle: f64,
    pub mirror: bool,
    /// Spans `doc.layout.instances`.
    pub instances: Span,
    pub bbox: BBox,
}

/// One materialized placement of a child step.
///
/// `transform` maps from the child step's local coordinate system into the
/// root layout coordinate system. Repeated boards, subpanels, coupons, and
/// tooling steps are all represented by this same structure.
#[derive(Debug, Clone)]
pub struct LayoutInstance<Symbol> {
    pub repeat: u32,
    pub parent_instance: Option<u32>,
    pub child_step: u32,
    pub source_step_ref: Symbol,
    pub parent_step_ref: Symbol,
    pub transform: Affine2,
    pub repeat_index_x: u32,
    pub repeat_index_y: u32,
    pub repeat_count_x: u32,
    pub repeat_count_y: u32,
    pub repeat_pitch_x: f64,
    pub repeat_pitch_y: f64,
    pub bbox: BBox,
}

/// A step's physical outline: one outer path plus material cutouts.
#[derive(Debug, Clone)]
pub struct StepProfile {
    /// Index into `doc.arena.paths`.
    pub outer_path: u32,
    /// Spans `doc.profile_cutouts`.
    pub cutouts: Span,
    pub bbox: BBox,
}

#[derive(Debug, Clone)]
pub struct StepProfileCutout {
    /// Index into `doc.arena.paths`.
    pub path: u32,
    pub bbox: BBox,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LayoutMargins {
    pub top: f64,
    pub right: f64,
    pub bottom: f64,
    pub left: f64,
}
