[package]
name = "pcb-docgen"
version = "0.1.0"
edition.workspace = true
description = "Generate documentation from Zener source files"

[dependencies]
anyhow = "1"
anstream = { workspace = true }
pcb-zen = { path = "../pcb-zen" }
pcb-zen-core = { path = "../pcb-zen-core" }
starlark = { workspace = true }
starlark_syntax = { workspace = true }
walkdir = "2"
